title: P.S Toronto Accessible E-Commerce Demo Store Blog
description: Everything you ever needed to know about accessibility and ecommerce.
timezone: 'America/New_York'
theme: jekyll-theme-slate
url: https://publicissapient.github.io/accessible-ecommerce/
comments: true
